export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTRE_REQUEST = 'USER_REGISTRE_REQUEST';
export const USER_REGISTRE_SUCCESS = 'USER_REGISTRE_SUCCESS';
export const USER_REGISTRE_FAIL = 'USER_REGISTRE_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';